/****************************************************************************
 * wx_freecell_app.cpp
 *
 * wxWidgets application entry point for FreeCell.
 ****************************************************************************/

#include "wx_freecell_app.h"
#include "wx_freecell_frame.h"

#include <wx/config.h>
#include <wx/filesys.h>
#include <wx/fs_arc.h>
#include <wx/fs_mem.h>
#include <wx/xrc/xmlres.h>

/* Generated by bin2c from the wxrc-compiled .xrs */
#include "freecell_xrs.h"

wxIMPLEMENT_APP(FreeCellApp);

bool FreeCellApp::OnInit()
{
    if (!wxApp::OnInit())
        return false;

    /* Set up application name for wxConfig */
    SetAppName("FreeCell");
    SetVendorName("FreeCell");

    /* Use wxFileConfig on all platforms for portability */
    wxConfigBase::Set(new wxConfig("FreeCell", "FreeCell"));

    /* Add BMP image handler */
    wxImage::AddHandler(new wxBMPHandler);

    /* Register filesystem handlers */
    wxFileSystem::AddHandler(new wxMemoryFSHandler);
    wxFileSystem::AddHandler(new wxArchiveFSHandler);

    /* Register the .xrs archive as a single file in the memory FS */
    wxMemoryFSHandler::AddFileWithMimeType(
        "XRC_resource/freecell.xrs",
        freecell_xrs, sizeof(freecell_xrs),
        "application/zip");

    /* Load XRC resources — wxXmlResource handles .xrs as zip archives */
    wxXmlResource::Get()->InitAllHandlers();
    wxXmlResource::Get()->Load("memory:XRC_resource/freecell.xrs");

    FreeCellFrame* frame = new FreeCellFrame();
    frame->Show(true);

    return true;
}
